name: Build
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Check format
        run: yarn format-check
      - name: Unit tests
        run: yarn test --coverage
      - name: Build
        run: yarn build
